Parameters:
  AssumeRoleName:
    Type: String
    Description: The name for the Border0 discovery role (for Border0 to assume).
    MinLength: 5
    AllowedPattern: ^[\w+=,.@:\/-]*$
    Default: 'Border0DiscoveryRole'
  AssumeRoleExternalId:
    Type: String
    Description: A (secret) string that Border0 must present in order to assume a role in the account.
    MinLength: 20
    AllowedPattern: ^[\w+=,.@:\/-]*$
  AllowRdsReadOnly:
    Description: 'Flag to attach RDS read-only IAM policy'
    Type: String
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'true'
  AllowEc2ReadOnly:
    Description: 'Flag to attach EC2 read-only IAM policy'
    Type: String
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'true'
  AllowEcsReadOnly:
    Description: 'Flag to attach ECS read-only IAM policy'
    Type: String
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'true'

Conditions:
  AttachRdsDiscoveryPolicy: !Equals [!Ref AllowRdsReadOnly, 'true']
  AttachEc2DiscoveryPolicy: !Equals [!Ref AllowEc2ReadOnly, 'true']
  AttachEcsDiscoveryPolicy: !Equals [!Ref AllowEcsReadOnly, 'true']

Resources:
  Border0DiscoveryRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref AssumeRoleName
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !Sub arn:aws:iam::774169227652:root # border0 staging
                - !Sub arn:aws:iam::235487987553:root # border0 production
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                sts:ExternalId: !Ref AssumeRoleExternalId
      ManagedPolicyArns:
        - !If [AttachRdsDiscoveryPolicy, 'arn:aws:iam::aws:policy/AmazonRDSReadOnlyAccess', !Ref "AWS::NoValue"]
        - !If [AttachEc2DiscoveryPolicy, 'arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess', !Ref "AWS::NoValue"]
  # there is no AWS managed ReadOnly policy for ECS, so we have to create one
  EcsReadOnlyPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: 'ECSReadOnlyPolicy'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: 'ECSReadOnly'
            Effect: 'Allow'
            Action:
              - 'ecs:DescribeClusters'
              - 'ecs:DescribeContainerInstances'
              - 'ecs:DescribeServices'
              - 'ecs:DescribeTaskDefinition'
              - 'ecs:DescribeTasks'
              - 'ecs:ListClusters'
              - 'ecs:ListContainerInstances'
              - 'ecs:ListServices'
              - 'ecs:ListTaskDefinitionFamilies'
              - 'ecs:ListTaskDefinitions'
              - 'ecs:ListTasks'
            Resource: '*'
      Roles: [!If [AttachEcsDiscoveryPolicy, !Ref Border0DiscoveryRole, !Ref "AWS::NoValue"]]

Outputs:
  Border0DiscoveryRoleARN:
    Description: "The ARN of the AWS IAM Role in this account for Border0 to assume."
    Value: !GetAtt Border0DiscoveryRole.Arn
  ExternalID:
    Description: "The (secret) string that Border0 must present in order to assume a role in the account."
    Value: !Ref AssumeRoleExternalId
